#!/usr/bin/env bash

install_files() {
  echo "Copying ./bin/* to ${SUBZERO_THEME_BIN}/"
  chmod +x ./bin/*
  cp -rf ./bin/* "${SUBZERO_THEME_BIN}/"

  echo "Copying ./Themes/* to ${SUBZERO_THEME_FILES}/"
  cp -rf ./Themes/* "${SUBZERO_THEME_FILES}/"

  echo "Copying font to $HOME/.local/share/fonts"
  mkdir -p "$HOME/.local/share/fonts"
  cp -rf ./Fonts/* "$HOME/.local/share/fonts/"
}

if [[ -v $SUBZERO_THEME_VERSION ]]; then
  INSTALLED_SUBZERO_THEME_VERSION=$SUBZERO_THEME_VERSION
  source ./Themes/SubZero_Version
  if [[ $INSTALLED_SUBZERO_THEME_VERSION != $SUBZERO_THEME_VERSION ]]; then
    echo "Updating Theme"
    read -p "Press enter to update..."
    install_files
    echo "Done!"
    exit
  else
    echo "Theme is already installed!"
    echo "Change the theme by pressing super+shift+c"
    exit
  fi
fi

read -p "Bin install directory (Needs to be in \$PATH) (~/.local/bin) > " SUBZERO_THEME_BIN
if [[ -z $SUBZERO_THEME_BIN ]]; then
  SUBZERO_THEME_BIN=$(echo "$HOME/.local/bin")
else
  SUBZERO_THEME_BIN=$(eval echo "${SUBZERO_THEME_BIN}")
  SUBZERO_THEME_BIN=$(realpath "${SUBZERO_THEME_BIN}")
fi
echo "Set bin install directory to ${SUBZERO_THEME_BIN}"

read -p "Theme files install directory (~/Themes) > " SUBZERO_THEME_FILES
if [[ -z $SUBZERO_THEME_FILES ]]; then
  SUBZERO_THEME_FILES="$HOME/Themes"
else
  SUBZERO_THEME_FILES=$(eval echo "${SUBZERO_THEME_FILES}")
  SUBZERO_THEME_FILES=$(realpath "${SUBZERO_THEME_FILES}")
fi
echo "Set bin install directory to ${SUBZERO_THEME_FILES}"

echo "Installing themes"
read -p "Press enter to install..."

mkdir $SUBZERO_THEME_BIN 2>/dev/null
mkdir $SUBZERO_THEME_FILES 2>/dev/null

export SUBZERO_THEME_BIN=$SUBZERO_THEME_BIN
export SUBZERO_THEME_FILES=$SUBZERO_THEME_FILES

cat << EOF > ~/.subzerorc
# SubZero Theme environment variables
# Gets automatically reset on update. Do not modify.
export SUBZERO_THEME_BIN="$SUBZERO_THEME_BIN"
export SUBZERO_THEME_FILES="$SUBZERO_THEME_FILES"
source \$SUBZERO_THEME_FILES/SubZero_Version
EOF

install_files

${SUBZERO_THEME_BIN}/thm default

echo "Done!"
